import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { QueryProvider } from "@/providers/query-provider";
import NewAccountSheet from "./features/accounts/components/new-account-sheet";
import { Toaster } from "@/components/ui/sonner";
import EditAccountSheet from "./features/accounts/components/edit-account-sheet";
import NewTransactionSheet from "./features/transactions/components/new-transaction-sheet";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
        <NewAccountSheet />
        <EditAccountSheet />
        <NewTransactionSheet />
          <Toaster />
        {children}
        </QueryProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
